[workspace]
members = [
    # -- Tools
    "tools/gen_key",

    # -- Application Libraries
    "libs/core",
    "libs/model",

    # -- Application Services
    "services/web-server"
]
# default-members to allow simple `cargo run`
default-members = ["services/web-server"]
