[package]
name = "rust-axum-intro"
version = "0.1.0"
edition = "2021"
authors = ["Jeremy Chone <jeremy.chone@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Rust Axum Full Course code."
homepage = "https://youtu.be/XZtlD_m59sM"
repository = "https://github.com/rust-httpc-test"

[dependencies]
tokio = { version = "1", features = ["full"] }
# -- Json
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = {version = "3", features = ["time_0_3"]}
# -- Web
axum = "0.6.16"
tower-http = { version = "0.4", features = ["fs"] }
tower-cookies = "0.9"
# -- Crypt & Encoding
rand = "0.8.5"
hmac = "0.12.1"
sha2 = "0.10.6"
uuid = {version = "1", features = ["v4", "fast-rng",]}
base64-url = "2"
# -- Data
sqlx = { version = "0.6", features = [ "runtime-tokio-rustls", "postgres", "uuid" ] }
sqlb = { path = "/Users/jeremychone/_jeremy/_rust/utils/rust-sqlb"}
mock-store = "0.2"
modql = "0.2"
# -- Others
lazy-regex = "2"
time = "0.3"
async-trait = "0.1"
strum_macros = "0.24"
once_cell = "1"
dotenvy = "0.15"



[dev-dependencies]
anyhow = "1"
httpc-test = "0.1.1"
